version: '2.3'

services:

  agent:
    image: gym_mupen64plus
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=:0
    volumes:
      - ./:/src
    network_mode: "host"
    command: python example.py
