name: gym-mupen64plus
channels:
- anaconda-fusion
- defaults
dependencies:
- openssl=1.0.2k=1
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - gym==0.17.3
  - numpy==1.14.2
  - PyYAML==3.12
  - termcolor==1.1.0
  - mss==3.2.0

