
from gym_mario_kart.envs.track_envs import MarioKartLuigiRacewayEnv
from gym_mario_kart.envs.track_envs import MarioKartMooMooFarmEnv
from gym_mario_kart.envs.track_envs import MarioKartKoopaTroopaBeachEnv
from gym_mario_kart.envs.track_envs import MarioKartKalimariDesertEnv
from gym_mario_kart.envs.track_envs import MarioKartToadsTurnpikeEnv
from gym_mario_kart.envs.track_envs import MarioKartFrappeSnowlandEnv
from gym_mario_kart.envs.track_envs import MarioKartChocoMountainEnv
from gym_mario_kart.envs.track_envs import MarioKartMarioRacewayEnv
from gym_mario_kart.envs.track_envs import MarioKartWarioStadiumEnv
from gym_mario_kart.envs.track_envs import MarioKartSherbetLandEnv
from gym_mario_kart.envs.track_envs import MarioKartRoyalRacewayEnv
from gym_mario_kart.envs.track_envs import MarioKartBowsersCastleEnv
from gym_mario_kart.envs.track_envs import MarioKartDKsJungleParkwayEnv
from gym_mario_kart.envs.track_envs import MarioKartYoshiValleyEnv
from gym_mario_kart.envs.track_envs import MarioKartBansheeBoardwalkEnv
from gym_mario_kart.envs.track_envs import MarioKartRainbowRoadEnv
